### ISSUE TITLE
These are my Three issue

### ISSUE THREAD

**Issue by JayantGoel001** [CSwala/Join-us#1]
Hello,
I just saw to join this organization we need to close three issue but it didn't contained any issue so is there any other repos to contribute to?

**Comment by riturajjain2000** [comment]
@JayantGoel001 The issues will be visible soon!!

**Comment by JayantGoel001** [comment]
@riturajjain2000 so until i can't join organisation?

**Comment by riturajjain2000** [comment]
@JayantGoel001  I fear not! Just hang in there, I will open the issues soon.

**Comment by JayantGoel001** [comment]
# 


> @JayantGoel001 I fear not! Just hang in there, I will open the issues soon.

Hey, @riturajjain2000 Add Me To Your Organization.
I assure you I will be of great help to you in maintaining this organization.
#3
#8
#21

**Comment by riturajjain2000** [comment]
Invitation Sent !! Welcome to the Org @JayantGoel001

**Comment by JayantGoel001** [comment]
@riturajjain2000 I think it will be great idea to create contributions repo in which when user add there name we will create webpage of the same. What do you think?

**Comment by riturajjain2000** [comment]
@JayantGoel001  For discussions you can join the discord server, mentioned in the Contribution.md file

**Comment by JayantGoel001** [comment]
@riturajjain2000 you removed from organization
I have done what was asked??
Any issues you want to discuss?
