### ISSUE TITLE
I wish to join this organization 

### ISSUE THREAD

**Issue by GowthamGoush** [CSwala/Join-us#6]
### Here are the three issues : 
 - [Issue 1](https://github.com/CSwala/CSwala-android/issues/91)
 - [Issue 2](https://github.com/CSwala/CSwala-android/issues/109)
 - [Issue 3](https://github.com/CSwala/CSwala-android/issues/124)
 
<div align="center">
<h4>Thank you!</h4>
</div>

**Comment by riturajjain2000** [comment]
Invite sent
