### ISSUE TITLE
For Joining the Org

### ISSUE THREAD

**Issue by saatviknagpal** [CSwala/Join-us#7]
Following are the 3 issues : 
* [Issue1](https://github.com/CSwala/awesome-computer-science/issues/523?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE5MDYyNDk2NjA6NjE2MTg3Njc%3D&notifications_query=is%3Adone#event-4718037095)
* [Issue2](https://github.com/CSwala/awesome-computer-science/issues/542?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE5MTU0MjMxMDk6NjE2MTg3Njc%3D&notifications_query=is%3Adone#event-4729209198)
* [Issue3](https://github.com/CSwala/awesome-computer-science/issues/507?notification_referrer_id=MDE4Ok5vdGlmaWNhdGlvblRocmVhZDE4OTQ2OTgyNDg6NjE2MTg3Njc%3D&notifications_query=is%3Adone#event-4718043580)

**Comment by riturajjain2000** [comment]
Invite Sent
