### ISSUE TITLE
For Joining the Org

### ISSUE THREAD

**Issue by ayushman999** [CSwala/Join-us#8]
I want to join the organization,
the issues that I've resolved are 
#My first issue [https://github.com/CSwala/CSwala-android/issues/99](url)
#My second issue [https://github.com/CSwala/CSwala-android/issues/160](url)
#My third issue [https://github.com/CSwala/CSwala-android/issues/174](url)

**Comment by riturajjain2000** [comment]
ok , just run the starme script and you will get an invite

**Comment by ayushman999** [comment]
I've copied and ran it once without editing anything. I don't have much experience with this type of code so tell me if something is wrong.

**Comment by riturajjain2000** [comment]
> I've copied and ran it once without editing anything. I don't have much experience with this type of code so tell me if something is wrong.

You did it right as there is a pending invite for you
