### ISSUE TITLE
Join organization

### ISSUE THREAD

**Issue by vikas780** [CSwala/Join-us#9]
> ### Hey there, i want to join this organizatin.
> ### Here are the three issues :
> * [Issue 1](https://github.com/CSwala/awesome-computer-science/issues/620)
> * [Issue 2](https://github.com/CSwala/awesome-computer-science/issues/497)
> * [Issue 3](https://github.com/CSwala/awesome-computer-science/issues/626)
> 
> #### Thank you!

**Comment by riturajjain2000** [comment]
Ok just run the starme script and you will get an invite!

**Comment by vikas780** [comment]
Not working bro.

**Comment by riturajjain2000** [comment]
Did you got the text in blue 'it finally over'?
BTW ,you have to copy it to the console and just have to press enter !

**Comment by vikas780** [comment]
yes, I got a text in blue, but after pasting the text to the console it is giving a syntax error.

**Comment by riturajjain2000** [comment]
not the text , you have to copy the entire script and paste to the console and press enter , then the text will appear

**Comment by vikas780** [comment]
**This is coming, bro.**

![Screenshot (236)](https://user-images.githubusercontent.com/54113274/119377387-b1fd6c00-bcda-11eb-882a-fd329f4eb74c.png)

**Comment by riturajjain2000** [comment]
Invite sent !
